CASES = [
    {
        "id": "CB-2025-001",
        "transaction_id": "TXN-8842-VISA",
        "cardholder": "Maria Santos",
        "amount": 289.99,
        "merchant": "ElectroMart MX",
        "merchant_id": "MERCH-4421",
        "network": "visa",
        "reason_code": "10.4",
        "claim": "Cardholder states they did not authorize this transaction. Purchase was made online from a device not recognized by them.",
        "days_since_txn": 18,
        "filing_date": "2025-04-10",
    },
    {
        "id": "CB-2025-002",
        "transaction_id": "TXN-5531-MC",
        "cardholder": "James Okonkwo",
        "amount": 149.00,
        "merchant": "StreamFlix Premium",
        "merchant_id": "MERCH-8891",
        "network": "mastercard",
        "reason_code": "4841",
        "claim": "Cardholder claims they cancelled their subscription 3 months ago but continue to be billed. No cancellation confirmation was ever received.",
        "days_since_txn": 5,
        "filing_date": "2025-04-24",
    },
    {
        "id": "CB-2025-003",
        "transaction_id": "TXN-3309-VISA",
        "cardholder": "Ana Herrera",
        "amount": 512.50,
        "merchant": "MobileFinance BR",
        "merchant_id": "MERCH-2234",
        "network": "visa",
        "reason_code": "13.1",
        "claim": "Cardholder states goods were never received. Order placed 45 days ago. Merchant provided a tracking number showing only label created, never shipped.",
        "days_since_txn": 45,
        "filing_date": "2025-04-15",
    },
    {
        "id": "CB-2025-004",
        "transaction_id": "TXN-7720-MC",
        "cardholder": "David Mensah",
        "amount": 75.00,
        "merchant": "PayJoy Device Plan",
        "merchant_id": "MERCH-0001",
        "network": "mastercard",
        "reason_code": "4853",
        "claim": "Cardholder claims the device received was a different color and model than advertised at time of purchase.",
        "days_since_txn": 12,
        "filing_date": "2025-04-18",
    },
    {
        "id": "CB-2025-005",
        "transaction_id": "TXN-9901-MC",
        "cardholder": "Carlos Mendez",
        "amount": 649.99,
        "merchant": "LuxGadgets NG",
        "merchant_id": "MERCH-7733",
        "network": "mastercard",
        "reason_code": "4863",
        "claim": "I have no knowledge of this transaction. I never shop at this merchant and did not authorize any purchase. Someone must have stolen my card details.",
        "days_since_txn": 28,
        "filing_date": "2025-04-25",
    },
]

TRANSACTION_DB: dict = {
    "TXN-8842-VISA": {
        "amount": 289.99,
        "currency": "USD",
        "merchant_name": "ElectroMart MX",
        "merchant_category": "Electronics Retail",
        "mcc": "5734",
        "authorization_code": "AUTH-449921",
        "avs_result": "Y",
        "cvv_result": "M",
        "device_fingerprint": "FP-8842-KNOWN-DEVICE",
        "prior_purchases_same_device": 4,
        "ip_address": "189.132.44.21",
        "ip_country": "MX",
        "billing_country": "MX",
        "shipping_address_match": True,
        "timestamp": "2025-03-23T14:32:00Z",
        "card_present": False,
        "three_ds_authenticated": True,
        "three_ds_eci": "05",
        "customer_signed_agreement": True,
        "notes": "3DS fully authenticated (ECI-05, liability shifts to issuer). Device fingerprint matches 4 prior cardholder purchases. AVS Y + CVV M. IP country matches billing country.",
    },
    "TXN-5531-MC": {
        "amount": 149.00,
        "currency": "USD",
        "merchant_name": "StreamFlix Premium",
        "merchant_category": "Digital Subscription",
        "mcc": "5967",
        "authorization_code": "AUTH-553142",
        "avs_result": "N/A",
        "cvv_result": "N/A",
        "device_fingerprint": "FP-5531-RECURRING",
        "ip_address": "102.89.31.5",
        "ip_country": "NG",
        "billing_country": "NG",
        "timestamp": "2025-04-19T09:00:00Z",
        "card_present": False,
        "three_ds_authenticated": False,
        "recurring": True,
        "cancellation_request_on_file": False,
        "cancellation_date_claimed": "2025-01-15",
        "service_usage_post_claimed_cancellation": True,
        "last_login_after_claimed_cancel": "2025-03-28T18:44:00Z",
        "terms_accepted_at_signup": True,
        "cancellation_policy_disclosed": True,
        "notes": "Recurring billing. No cancellation request on file. Service actively accessed 2025-03-28, 72 days after claimed cancellation date of Jan 15.",
    },
    "TXN-3309-VISA": {
        "amount": 512.50,
        "currency": "BRL",
        "merchant_name": "MobileFinance BR",
        "merchant_category": "Mobile Device Financing",
        "mcc": "6012",
        "authorization_code": "AUTH-330944",
        "avs_result": "P",
        "cvv_result": "M",
        "device_fingerprint": "FP-3309-NEW-DEVICE",
        "ip_address": "200.131.100.44",
        "ip_country": "BR",
        "billing_country": "BR",
        "shipping_address_match": False,
        "timestamp": "2025-02-28T11:18:00Z",
        "card_present": False,
        "three_ds_authenticated": False,
        "tracking_number": "BR88442201033",
        "tracking_status": "LABEL_CREATED",
        "tracking_last_carrier_scan": None,
        "days_since_order": 45,
        "notes": "Tracking label created but no carrier scan ever recorded. Shipping address differs from billing. No 3DS. New device fingerprint not seen before.",
    },
    "TXN-7720-MC": {
        "amount": 75.00,
        "currency": "USD",
        "merchant_name": "PayJoy Device Plan",
        "merchant_category": "Consumer Electronics Financing",
        "mcc": "6012",
        "authorization_code": "AUTH-772003",
        "avs_result": "Y",
        "cvv_result": "M",
        "device_fingerprint": "FP-7720-ENROLLED",
        "ip_address": "41.202.219.88",
        "ip_country": "GH",
        "billing_country": "GH",
        "shipping_address_match": True,
        "timestamp": "2025-04-17T16:45:00Z",
        "card_present": False,
        "three_ds_authenticated": False,
        "product_sku": "SAMSUNG-A55-BLACK-128",
        "product_description_at_purchase": "Samsung Galaxy A55 5G – Phantom Black, 128GB",
        "customer_signed_agreement": True,
        "loan_agreement_on_file": True,
        "device_imei": "359823110234567",
        "device_imei_registered_to_cardholder": True,
        "prior_complaint_on_file": False,
        "notes": "Signed loan agreement on file. Product SKU exactly matches order confirmation. Device IMEI registered to cardholder. No prior complaint submitted.",
    },
    "TXN-9901-MC": {
        "amount": 649.99,
        "currency": "USD",
        "merchant_name": "LuxGadgets NG",
        "merchant_category": "Electronics Retail",
        "mcc": "5732",
        "authorization_code": "AUTH-990122",
        "avs_result": "Y",
        "cvv_result": "M",
        "device_fingerprint": "FP-9901-CARDHOLDER-PRIMARY",
        "prior_purchases_same_device": 6,
        "ip_address": "197.211.58.43",
        "ip_country": "NG",
        "billing_country": "NG",
        "shipping_address_match": True,
        "timestamp": "2025-03-28T11:05:00Z",
        "card_present": False,
        "three_ds_authenticated": True,
        "three_ds_eci": "02",
        "delivery_status": "DELIVERED_SIGNED",
        "delivery_signature": "C. Mendez",
        "delivery_confirmed_date": "2025-03-29T14:30:00Z",
        "product_serial": "LX-LAPTOP-PRO-2024-SN44821",
        "product_activated_with_cardholder_email": True,
        "product_activation_date": "2025-03-30T14:22:00Z",
        "cardholder_account_login_post_delivery": True,
        "last_login_from_same_device": "2025-04-05T09:15:00Z",
        "chargeback_filed_days_after_delivery": 26,
        "notes": (
            "3DS ECI-02 authenticated (frictionless, issuer confirmed). "
            "Device is cardholder's primary device with 6 prior transactions. "
            "Product activated with cardholder's registered email 25 hours after delivery. "
            "Delivery signed by 'C. Mendez'. "
            "Cardholder logged in from same device 7 days post-delivery. "
            "Chargeback filed 26 days after confirmed delivery — classic friendly-fraud delay pattern."
        ),
    },
}

REASON_CODE_DB: dict = {
    "visa_10.4": {
        "name": "Other Fraud – Card Absent Environment",
        "description": "Cardholder claims they did not authorize a card-not-present transaction",
        "chargeback_time_limit_days": 120,
        "representment_time_limit_days": 30,
        "key_evidence_required": [
            "3DS authentication proof (ECI 05/02)",
            "AVS + CVV match results",
            "Device fingerprint with prior purchase history",
            "IP geolocation vs billing address",
            "Signed cardholder agreement",
        ],
        "fight_indicators": [
            "3DS ECI-05 (full authentication, liability shifts to issuer)",
            "Device fingerprint matches prior purchases",
            "AVS Y + CVV M",
            "IP country matches billing country",
        ],
        "accept_indicators": [
            "No 3DS or ECI-07",
            "AVS mismatch",
            "New device fingerprint",
            "IP in different country than billing",
        ],
        "win_rate_benchmark": 0.72,
    },
    "mastercard_4841": {
        "name": "Cancelled Recurring or Digital Goods Transaction",
        "description": "Cardholder claims they cancelled a recurring service but continues to be billed",
        "chargeback_time_limit_days": 120,
        "representment_time_limit_days": 45,
        "key_evidence_required": [
            "Proof no cancellation request was ever received",
            "Evidence of continued service access post-claim",
            "Cancellation policy shown at signup",
            "Terms of service acknowledgment",
        ],
        "fight_indicators": [
            "No cancellation request on file",
            "Service actively used after claimed cancellation date",
            "Clear T&C with cancellation procedure accepted",
        ],
        "accept_indicators": [
            "Written cancellation request exists",
            "No service usage after claimed cancellation",
            "Cancellation policy not clearly disclosed",
        ],
        "win_rate_benchmark": 0.65,
    },
    "visa_13.1": {
        "name": "Merchandise/Services Not Received",
        "description": "Cardholder claims goods or services were never received",
        "chargeback_time_limit_days": 120,
        "representment_time_limit_days": 30,
        "key_evidence_required": [
            "Carrier scan confirming delivery",
            "Signed delivery confirmation",
            "Proof delivered to correct address",
            "Tracking must show actual carrier movement (not just label created)",
        ],
        "fight_indicators": [
            "Full carrier delivery scan",
            "Signature on delivery",
            "Delivery to billing address",
        ],
        "accept_indicators": [
            "Tracking shows only label created",
            "No carrier scan in 45+ days",
            "Shipping address mismatch",
            "No delivery confirmation",
        ],
        "win_rate_benchmark": 0.38,
    },
    "mastercard_4853": {
        "name": "Cardholder Dispute – Not as Described or Defective Merchandise",
        "description": "Cardholder claims received product significantly differed from description",
        "chargeback_time_limit_days": 120,
        "representment_time_limit_days": 45,
        "key_evidence_required": [
            "Product listing/description at time of purchase",
            "Proof product matched description (SKU, photos, model specs)",
            "Signed order agreement",
            "Evidence cardholder did not attempt to return",
        ],
        "fight_indicators": [
            "SKU and product description exactly match",
            "Signed loan/order agreement on file",
            "IMEI/serial number registered to cardholder",
            "No prior complaint filed",
        ],
        "accept_indicators": [
            "Product description vague or misleading",
            "Photos prove different item shipped",
            "No signed agreement",
        ],
        "win_rate_benchmark": 0.61,
    },
    "mastercard_4863": {
        "name": "Cardholder Does Not Recognize – No Cardholder Authorization",
        "description": "Cardholder claims to have no knowledge of the transaction and denies authorization",
        "chargeback_time_limit_days": 120,
        "representment_time_limit_days": 45,
        "key_evidence_required": [
            "3DS authentication proof",
            "Device fingerprint matching cardholder's known device history",
            "Delivery confirmation with cardholder signature",
            "Evidence of product use or activation by cardholder post-delivery",
            "IP geolocation consistency with cardholder billing address",
        ],
        "fight_indicators": [
            "3DS ECI-02 authenticated (frictionless, issuer-confirmed)",
            "Device fingerprint matches 6+ prior cardholder purchases",
            "Delivery signed by cardholder name",
            "Product activated using cardholder's registered email within 48h of delivery",
            "Cardholder account logged in from same device post-delivery",
            "IP country matches billing country",
            "Chargeback filed 26 days post-delivery — inconsistent with genuine fraud claim",
        ],
        "accept_indicators": [
            "No 3DS authentication",
            "No delivery confirmation",
            "New device fingerprint with no prior history",
            "IP country mismatch",
        ],
        "friendly_fraud_note": (
            "MC 4863 is the most common vector for first-party misuse (friendly fraud). "
            "Key indicators: late chargeback filing (20+ days post-delivery), product activation "
            "by cardholder post-delivery, login activity from cardholder's primary device. "
            "When these indicators are present, recommend FIGHT and flag for friendly-fraud pattern tracking."
        ),
        "win_rate_benchmark": 0.69,
    },
}

MERCHANT_DB: dict = {
    "MERCH-4421": {
        "name": "ElectroMart MX",
        "total_disputes": 142,
        "won": 103,
        "lost": 39,
        "dispute_ratio": 0.008,
        "common_reason_codes": ["10.4", "13.1"],
        "avg_txn_value": 215,
        "months_on_platform": 28,
    },
    "MERCH-8891": {
        "name": "StreamFlix Premium",
        "total_disputes": 89,
        "won": 58,
        "lost": 31,
        "dispute_ratio": 0.021,
        "common_reason_codes": ["4841", "4853"],
        "avg_txn_value": 99,
        "months_on_platform": 14,
    },
    "MERCH-2234": {
        "name": "MobileFinance BR",
        "total_disputes": 67,
        "won": 27,
        "lost": 40,
        "dispute_ratio": 0.034,
        "common_reason_codes": ["13.1", "10.4"],
        "avg_txn_value": 380,
        "months_on_platform": 9,
    },
    "MERCH-0001": {
        "name": "PayJoy Device Plan",
        "total_disputes": 203,
        "won": 161,
        "lost": 42,
        "dispute_ratio": 0.011,
        "common_reason_codes": ["4853", "4841"],
        "avg_txn_value": 125,
        "months_on_platform": 48,
    },
    "MERCH-7733": {
        "name": "LuxGadgets NG",
        "total_disputes": 54,
        "won": 39,
        "lost": 15,
        "dispute_ratio": 0.015,
        "common_reason_codes": ["4863", "4853"],
        "avg_txn_value": 520,
        "months_on_platform": 18,
        "friendly_fraud_rate": 0.31,
        "notes": "31% of disputes identified as first-party misuse (friendly fraud). Strong representment track record on 4863 cases with 3DS + delivery evidence.",
    },
}
